export type { UnresolvedCallBucket, UnresolvedCallDiagnostic } from "./diagnostics"
export type {
  ComponentOverride,
  Config,
  FrameworkHint,
  HintRule,
  LspServerConfig,
  PluginRef as ConfigPluginRef,
} from "./generated/config"
export type {
  ArrayDelta,
  ComponentDiff,
  DependencyDiff,
  DependencyUnknown,
  DiffResult,
  Generator as DiffGenerator,
  IRRef,
  MatchRationale,
  NotComparedFile,
  SignatureDelta,
  SkippedFile as DiffSkippedFile,
  SkipReason,
  SliceId,
  SliceRecord,
  Summary,
  SymbolAdded,
  SymbolChange,
  SymbolChanged,
  SymbolDelta,
  SymbolDroppedToggled,
  SymbolMoved,
  SymbolMovedChanged,
  SymbolRemoved,
  SymbolUnknown,
} from "./generated/diff"
export type {
  Call,
  CallResolutionStats,
  Component,
  ComponentId,
  Confidence,
  Decorator,
  Dependency,
  DependencyEndpoint,
  Effect,
  EffectClassifyTimeout,
  EffectId,
  EffectPropagationStats,
  ExtKind,
  Fingerprint,
  Generator,
  IR,
  LanguageId,
  LspEnrichmentStats,
  LspHintRejections,
  PluginRef,
  RelativePath,
  Rule,
  RuleType,
  Signature,
  SkippedFile,
  SourceRange,
  Stats,
  Symbol,
  Symbol as IRSymbol,
  SymbolId,
  SymbolKind,
  UnresolvedCallBuckets,
  Visibility,
  Workspace,
  WorkspaceManager,
} from "./generated/ir"
export type {
  Capabilities,
  EffectVocab as ManifestEffectVocab,
  ExtKindVocab as ManifestExtKindVocab,
  PluginManifest,
  Provides,
} from "./generated/plugin"
export type {
  BodyExtraction,
  CallCandidate,
  ClassifyContext,
  DropHint,
  EffectClassification,
  EffectPlugin,
  EffectsManifest,
  EffectVocab,
  ExtKindVocab,
  ExtractionContext,
  FileSummary,
  FrameworkClassifyContext,
  FrameworkManifest,
  FrameworkPlugin,
  FrameworkVocab,
  ImportBinding,
  ImportEdge,
  LangManifest,
  LanguageCapabilities,
  LanguagePlugin,
  Logger,
  MergedDeclaration,
  OpaqueAstNode,
  OwnerDecorator,
  OwnerSummary,
  ParsedTree,
  ParseError,
  ParseResult,
  PluginContext,
  SourceFile,
  SymbolCandidate,
  SymbolClassification,
  VocabRegistry,
  WalkContext,
  WrittenSourceRange,
} from "./plugins"
export { COMPUTED_TARGET_SEGMENT, UNNAMED_DECORATOR } from "./vocabulary"
