import type { LangManifest } from "@aburi/types"

export const langTypescriptManifest: LangManifest = {
  $schema: "https://aburi.kage1020.com/schema/aburi.plugin.v1.json",
  name: "lang-typescript",
  version: "0.0.0",
  type: "lang",
  engines: { aburi: "*" },
  provides: {
    effects: [],
    effectPrefixes: [],
    extKinds: [],
    extKindPrefixes: [],
    derivedByPrefixes: [
      "export-keyword",
      "export-default",
      "variable-assigned-function",
      "class-method",
      "field-assigned-function",
      "inline-handler",
      "call-argument-function",
      "object-literal-initializer",
      "object-method",
      "property-assigned-function",
      "static-method",
      "interface-declaration",
      "type-alias",
      "namespace-declaration",
      "enum-declaration",
      "constructor-declaration",
      "destructured-binding",
      "accessor-declaration",
      "abstract-declaration",
      "ambient-declaration",
      "declaration-merged",
    ],
    frameworks: [],
  },
  capabilities: {
    wasmHeapPerWorkerMB: 256,
  },
}
